// Automatically generated by astro-icon
// 782b738d34ae261877fa07781233e64f68a21063eb908e6d25d75072014fadfd

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "building"
		| "handshake"
		| "house"
		| "phone"
		| "search";
}