// Automatically generated by astro-icon
// 57f51652d9b9bbc46490e26c18bfd2283b8f7c0a826a156ea2b77e94a5e44898

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "building"
		| "chevronLeft"
		| "chevronRight"
		| "facebook"
		| "halfStar"
		| "handshake"
		| "house"
		| "instagram"
		| "linkedin"
		| "phone"
		| "search"
		| "star"
		| "x";
}