// Automatically generated by astro-icon
// 7ae96eca2d3aa1981b82924507a5a82e9b70ddb7a0d5ed8fc56aaa19a2160df4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "building"
		| "chevronLeft"
		| "chevronRight"
		| "halfStar"
		| "handshake"
		| "house"
		| "phone"
		| "search"
		| "star";
}